/*
 DXLong.js (c) 2013 Daniel Wirtz <dcode@dcode.io>
 Released under the Apache License, Version 2.0
 see: https://github.com/dcodeIO/DXLong.js for details
*/
var bt={STRING:0,BYTE:1,SHORT:2,BOOLEAN:3,INT:4,BYTES:5,LONG:8,ARRAY_INT:9,ARRAY_LONG:10,ARRAY_ARRAY:11,PACKET:100},deviceInfo=function(){deviceType=2;setDeviceType=function(a){try{this.deviceType=parseInt(a,10),this.deviceType!==this.deviceType&&(this.deviceType=2)}catch(b){console.error(b)}}},SVID_BASE=3E4,constant={SVID_DEAMON:1,SVID_LVS:2,SVID_LOGIN:3,SVID_ROUTER:4,SVID_BRIDGE:5,SVID_CALL_SIGNAL:12,SVID_UAUTH:99,SVID_ONLINE:101,SVID_MSG:201,SVID_MSG_LOGIC:202,SVID_PUSH:301,SVID_PUSH_PROXY:302,
SVID_IM:401,SVID_PUB:410,SVID_KEFU:415,SVID_DATA:1101,SVID_CORP:801,SVID_TPT:501,SVID_TPT_PROXY:502,SVID_TPT2U:503,SVID_TPT2S:504,SVID_CHATROOM:420,SVID_BASE:SVID_BASE,URI_BASE_PING:SVID_BASE<<16|10,URI_BASE_PONG:SVID_BASE<<16|11,URI_UNI_TRANSUP:SVID_BASE<<16|4,URI_UNI_TRANSP2P:SVID_BASE<<16|6,URI_UNI_TRANSUPGRP:SVID_BASE<<16|7,URI_UNI_TRANSPLATDEST:SVID_BASE<<16|9,APPID_XMAPP:1,PACKET_HEAD_LENGTH:10,PROTO_TCP_BUFFER_SIZE:32768,PROTO_UDP_BUFFER_SIZE:16384,PROTO_PACKET_SIZE:1024,PROTO_POOL_SIZE:1024,
RES_NONSENSE:-1,RES_TIMEOUT:-2,RES_SUCCESS:0,RES_FAIL:1,RES_OVERLOAD:2,RES_INVAID_ISP:3,RES_NO_GROUP:4,RES_NO_SESSION:5,RES_NO_USER:6,RES_INVALID_PASSWORD:7,RES_SESSION_OVERFLOW:8,RES_BUSY:9,RES_REJECT:10,RES_INVALID_STREAM:11,RES_STREAM_EXIST:12,RES_EXISTS:13,RES_SERVER_NOT_READY:14,RES_NO_UID:15,RES_DUPLICATION:16,RES_INVALID_PARAMS:17,RES_INVALID_CODE:18,RES_INVALID_COOKIE:19,RES_EXPIRE_COOKIE:20,RES_NO_PASSPORT:21,RES_NO_PASSWORD:22,RES_NO_DEVICE_ID:23,RES_NO_COOKIE:24,RES_AUTH_TIMEOUT:25,RES_ONLINE_SYNC_TIMEOUT:26,
RES_NOT_ENCRYPTED:27,RES_SQL_ERROR:99,RES_NET_BROKEN:100,RES_NO_RESPONSE:101,RES_CANCELING:102,RES_HTTP_SUCCESS:200,RES_NOT_FOUND:404,RES_FORBIDDEN:1E3,sessionType:{CHAT:"chat",GROUP_CHAT:"groupchat",PUB_CHAT:"pubchat",CS_CHAT:"cschat",KEFU_CHAT:"kefuchat"},Message:{MSG_TYPE_TEXT:1,MSG_TYPE_VOICE:2,MSG_TYPE_VIDEO:3,MSG_TYPE_IMAGE:4,MSG_TYPE_CALENDAR:5,MSG_TYPE_LINK:6,MSG_TYPE_MULTI_LINK:7,MSG_TYPE_FILE:8,MSG_TYPE_GPS:9,MSG_TYPE_VCARD:10,MSG_TYPE_EMOTION:11,MSG_TYPE_EVENT:12,MSG_TYPE_CUSTOM:13,MSG_TYPE_NOTICE:14,
MSG_TYPE_PCALL:15,MSG_TYPE_RED_PACKET:16,MSG_TYPE_GENERAL:17,MSG_TYPE_GVCARD:18,MSG_TYPE_NEWEMOTION:19,MSG_TYPE_TT:100},GENERAL_TYPE:{TYPE_CALL_1V1:1,TYPE_CALL_MEETING:2,TYPE_GROUP_VOTE:3},CipherType:{NO_CIPHER:0,AES:1,RSA:2,RC4:3,BASE64:4},LOGIN_EVENT:{AUTH_SUCCESS:"AuthSuccess",AUTH_FAIL:"AuthFail",KICK_OFF:"KickOff",USE_BOSH:"use_bosh",DISCONNECT:"disconnect"},SESSION_EVENT:{INIT_SESSION_LIST:"init_session_list",UPDATE_SESSIONS:"update_session"},MESSAGE_EVENT:{MESSAGE:"message",T_MESSAGE:"T_message",
D_MESSAGE:"dMessage",ACK:"ack",READ:"read",IM_READ:"im_read",PUB_READ:"pub_read",NOTICE:"notice",RECEIPT_ACK:"receiptACK",SAVE_MESSAGE:"save_message",K_MESSAGE:"K_message",K_ACK:"K_ack",K_READ:"K_read",K_NOTICE:"K_Notice"},CALL_EVENT:{CREATE_ACK:"callCreateAck",INVITE_ACK:"callInviteAck",INVITE:"callInvite",DETECT_ACK:"detectAck",INVITE_RESPONSE_ACK:"inviteResponseAck",JOIN:"callJoin",PING_ACK:"callPingAck",MEMBER_CHANGE:"callMemberChange",NOTICE:"callNotice",QUALITY_NOTICE:"callQualityNotice",LEAVE:"callLeave"},
MESSAGE_STATUS:{STATUS_CREATED:0,STATUS_SENT:1,STATUS_TIMEOUT:2,STATUS_ACK:3,STATUS_UNREAD:4,STATUS_READ:5,STATUS_SEND_ERR:6},CANCEL_STATUS:{CANCELING:"canceling",CANCELED:"canceled"},MESSAGE_SOURCE:{FROM_ONLINE:1,FROM_OFFLINE:2,FROM_HISTORY:3,FROM_SESSIONLIST:4},LOGIN_STATUS:{ERROR:-1,CONNECTING:1,CONNECTED:2,EXCHANGING:3,EXCHANGED:4,AUTHENTICATING:5,AUTHENTICATED:6,DISCONNECTING:7,DISCONNECTED:8,TERMINATED:9},OWL_NAME:{SEND_MESSAGE_TIME:"sendMessageTime"},CHAT_TYPE:{CHAT_TYPE_ONE_VS_ONE:1,CHAT_TYPE_GROUP:2,
CHAT_TYPE_PUB:1,CHAT_TYPE_CS:2},AUTOLOGIN:!0},svidLogin=constant.SVID_MSG_LOGIC,httpConstant=constant;httpConstant.HTTP={URI_MSG_HISTORY_REQ:svidLogin<<16|10,URI_MSG_HISTORY_RES:svidLogin<<16|11,URI_MSG_CHATLIST_REQ:svidLogin<<16|12,URI_MSG_CHATLIST_RES:svidLogin<<16|13};
var b64map="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",_base64={encode:function(a){var b="",c=0;do{var d=a.charCodeAt(c++),e=a.charCodeAt(c++),f=a.charCodeAt(c++);d=d?d:0;e=e?e:0;f=f?f:0;var g=d>>2&63;d=(d&3)<<4|e>>4&15;var h=(e&15)<<2|f>>6&3,l=f&63;e?f||(l=64):h=l=64;b+=b64map.charAt(g)+b64map.charAt(d)+b64map.charAt(h)+b64map.charAt(l)}while(c<a.length);return b},decode:function(a){var b="",c=0;do{var d=b64map.indexOf(a.charAt(c++)),e=b64map.indexOf(a.charAt(c++)),f=b64map.indexOf(a.charAt(c++)),
g=b64map.indexOf(a.charAt(c++)),h=(e&15)<<4|f>>2&15;f=(f&3)<<6|g&63;b+=String.fromCharCode((d&63)<<2|e>>4&3)+(h?String.fromCharCode(h):"")+(f?String.fromCharCode(f):"")}while(c<a.length);return b}};function utf16to8(a){var b;var c="";var d=a.length;for(b=0;b<d;b++){var e=a.charCodeAt(b);1<=e&&127>=e?c+=a.charAt(b):(2047<e?(c+=String.fromCharCode(224|e>>12&15),c+=String.fromCharCode(128|e>>6&63)):c+=String.fromCharCode(192|e>>6&31),c+=String.fromCharCode(128|e>>0&63))}return c}
function utf8to16(a){var b;var c="";var d=a.length;for(b=0;b<d;){var e=a.charCodeAt(b++);switch(e>>4){case 0:case 1:case 2:case 3:case 4:case 5:case 6:case 7:c+=a.charAt(b-1);break;case 12:case 13:var f=a.charCodeAt(b++);c+=String.fromCharCode((e&31)<<6|f&63);break;case 14:f=a.charCodeAt(b++);var g=a.charCodeAt(b++);c+=String.fromCharCode((e&15)<<12|(f&63)<<6|(g&63)<<0)}}return c}function int2char(a){return"0123456789abcdefghijklmnopqrstuvwxyz".charAt(a)}
function b64tohex(a){var b="",c,d=0;for(c=0;c<a.length&&"="!=a.charAt(c);++c){var e=b64map.indexOf(a.charAt(c));if(!(0>e))if(0==d){b+=int2char(e>>2);var f=e&3;d=1}else 1==d?(b+=int2char(f<<2|e>>4),f=e&15,d=2):2==d?(b+=int2char(f),b+=int2char(e>>2),f=e&3,d=3):(b+=int2char(f<<2|e>>4),b+=int2char(e&15),d=0)}1==d&&(b+=int2char(f<<2));return b}function b64toBA(a){a=b64tohex(a);var b,c=[];for(b=0;2*b<a.length;++b)c[b]=parseInt(a.substring(2*b,2*b+2),16);return c}
var base64={encode:function(a){return _base64.encode(utf16to8(a))},decode:function(a){return utf8to16(_base64.decode(a))},BAtob64:function(a){var b,c=a.length,d="";if(a.get)for(b=0;b<c;b+=3)a.get(b),d+=b64map[a.get(b)>>2],d+=b64map[(a.get(b)&3)<<4|a.get(b+1)>>4],d+=b64map[(a.get(b+1)&15)<<2|a.get(b+2)>>6],d+=b64map[a.get(b+2)&63];else for(b=0;b<c;b+=3)d+=b64map[a[b]>>2],d+=b64map[(a[b]&3)<<4|a[b+1]>>4],d+=b64map[(a[b+1]&15)<<2|a[b+2]>>6],d+=b64map[a[b+2]&63];2===c%3?d=d.substring(0,d.length-1)+"=":
1===c%3&&(d=d.substring(0,d.length-2)+"==");return d},b64toBA:function(a){return new Uint8Array(b64toBA(a))}},DXLong=function(a,b,c){this.low=a|0;this.high=b|0;this.unsigned=!!c};DXLong.isDXLong=function(a){return!0===(a&&a instanceof DXLong)};var INT_CACHE={},UINT_CACHE={};
DXLong.fromInt=function(a,b){var c;if(b){a>>>=0;if(0<=a&&256>a&&(c=UINT_CACHE[a]))return c;c=new DXLong(a,0>(a|0)?-1:0,!0);0<=a&&256>a&&(UINT_CACHE[a]=c)}else{a|=0;if(-128<=a&&128>a&&(c=INT_CACHE[a]))return c;c=new DXLong(a,0>a?-1:0,!1);-128<=a&&128>a&&(INT_CACHE[a]=c)}return c};
DXLong.fromNumber=function(a,b){b=!!b;return isNaN(a)||!isFinite(a)?DXLong.ZERO:!b&&a<=-TWO_PWR_63_DBL?DXLong.MIN_VALUE:!b&&a+1>=TWO_PWR_63_DBL?DXLong.MAX_VALUE:b&&a>=TWO_PWR_64_DBL?DXLong.MAX_UNSIGNED_VALUE:0>a?DXLong.fromNumber(-a,b).negate():new DXLong(a%TWO_PWR_32_DBL|0,a/TWO_PWR_32_DBL|0,b)};DXLong.fromBits=function(a,b,c){return new DXLong(a,b,c)};
DXLong.fromString=function(a,b,c){if(0===a.length)throw Error("number format error: empty string");if("NaN"===a||"Infinity"===a||"+Infinity"===a||"-Infinity"===a)return DXLong.ZERO;"number"===typeof b&&(c=b,b=!1);c=c||10;if(2>c||36<c)throw Error("radix out of range: "+c);var d;if(0<(d=a.indexOf("-")))throw Error('number format error: interior "-" character: '+a);if(0===d)return DXLong.fromString(a.substring(1),b,c).negate();d=DXLong.fromNumber(Math.pow(c,8));for(var e=DXLong.ZERO,f=0;f<a.length;f+=
8){var g=Math.min(8,a.length-f),h=parseInt(a.substring(f,f+g),c);8>g?(g=DXLong.fromNumber(Math.pow(c,g)),e=e.multiply(g).add(DXLong.fromNumber(h))):(e=e.multiply(d),e=e.add(DXLong.fromNumber(h)))}e.unsigned=b;return e};DXLong.fromValue=function(a,b){return"number"===typeof a?DXLong.fromNumber(a,b):"string"===typeof a?DXLong.fromString(a,b):DXLong.isDXLong(a)?a:new DXLong(a.low,a.high,a.unsigned)};
var TWO_PWR_16_DBL=65536,TWO_PWR_24_DBL=16777216,TWO_PWR_32_DBL=TWO_PWR_16_DBL*TWO_PWR_16_DBL,TWO_PWR_64_DBL=TWO_PWR_32_DBL*TWO_PWR_32_DBL,TWO_PWR_63_DBL=TWO_PWR_64_DBL/2,TWO_PWR_24=DXLong.fromInt(TWO_PWR_24_DBL);DXLong.ZERO=DXLong.fromInt(0);DXLong.UZERO=DXLong.fromInt(0,!0);DXLong.ONE=DXLong.fromInt(1);DXLong.UONE=DXLong.fromInt(1,!0);DXLong.NEG_ONE=DXLong.fromInt(-1);DXLong.MAX_VALUE=DXLong.fromBits(-1,2147483647,!1);DXLong.MAX_UNSIGNED_VALUE=DXLong.fromBits(-1,-1,!0);
DXLong.MIN_VALUE=DXLong.fromBits(0,-2147483648,!1);DXLong.prototype.toInt=function(){return this.unsigned?this.low>>>0:this.low};DXLong.prototype.toNumber=function(){return this.unsigned?(this.high>>>0)*TWO_PWR_32_DBL+(this.low>>>0):this.high*TWO_PWR_32_DBL+(this.low>>>0)};
DXLong.prototype.value=function(a){a=a||10;if(2>a||36<a)throw RangeError("radix out of range: "+a);if(this.isZero())return"0";if(this.isNegative()){if(this.equals(DXLong.MIN_VALUE)){var b=DXLong.fromNumber(a);var c=this.div(b);b=c.multiply(b).subtract(this);return c.value(a)+b.toInt().value(a)}return"-"+this.negate().value(a)}c=DXLong.fromNumber(Math.pow(a,6),this.unsigned);b=this;for(var d="";;){var e=b.div(c),f=(b.subtract(e.multiply(c)).toInt()>>>0).toString(a);b=e;if(b.isZero())return f+d;for(;6>
f.length;)f="0"+f;d=""+f+d}};DXLong.prototype.toString=DXLong.prototype.value;DXLong.prototype.getNumBitsAbs=function(){if(this.isNegative())return this.equals(DXLong.MIN_VALUE)?64:this.negate().getNumBitsAbs();for(var a=0!=this.high?this.high:this.low,b=31;0<b&&0==(a&1<<b);b--);return 0!=this.high?b+33:b+1};DXLong.prototype.isZero=function(){return 0===this.high&&0===this.low};DXLong.prototype.isNegative=function(){return!this.unsigned&&0>this.high};
DXLong.prototype.isOdd=function(){return 1===(this.low&1)};DXLong.prototype.equals=function(a){DXLong.isDXLong(a)||(a=DXLong.fromValue(a));return this.unsigned!==a.unsigned&&1===this.high>>>31&&1===a.high>>>31?!1:this.high===a.high&&this.low===a.low};DXLong.prototype.lessThan=function(a){DXLong.isDXLong(a)||(a=DXLong.fromValue(a));return 0>this.compare(a)};DXLong.prototype.greaterThan=function(a){DXLong.isDXLong(a)||(a=DXLong.fromValue(a));return 0<this.compare(a)};
DXLong.prototype.greaterThanOrEqual=function(a){return 0<=this.compare(a)};DXLong.prototype.compare=function(a){if(this.equals(a))return 0;var b=this.isNegative(),c=a.isNegative();return b&&!c?-1:!b&&c?1:this.unsigned?a.high>>>0>this.high>>>0||a.high===this.high&&a.low>>>0>this.low>>>0?-1:1:this.subtract(a).isNegative()?-1:1};DXLong.prototype.negate=function(){return!this.unsigned&&this.equals(DXLong.MIN_VALUE)?DXLong.MIN_VALUE:this.not().add(DXLong.ONE)};
DXLong.prototype.add=function(a){DXLong.isDXLong(a)||(a=DXLong.fromValue(a));var b=this.high>>>16,c=this.high&65535,d=this.low>>>16,e=a.high>>>16,f=a.high&65535,g=a.low>>>16;a=(this.low&65535)+(a.low&65535);g=(a>>>16)+(d+g);d=g>>>16;d+=c+f;b=(d>>>16)+(b+e)&65535;return DXLong.fromBits((g&65535)<<16|a&65535,b<<16|d&65535,this.unsigned)};DXLong.prototype.subtract=function(a){DXLong.isDXLong(a)||(a=DXLong.fromValue(a));return this.add(a.negate())};
DXLong.prototype.multiply=function(a){if(this.isZero())return DXLong.ZERO;DXLong.isDXLong(a)||(a=DXLong.fromValue(a));if(a.isZero())return DXLong.ZERO;if(this.equals(DXLong.MIN_VALUE))return a.isOdd()?DXLong.MIN_VALUE:DXLong.ZERO;if(a.equals(DXLong.MIN_VALUE))return this.isOdd()?DXLong.MIN_VALUE:DXLong.ZERO;if(this.isNegative())return a.isNegative()?this.negate().multiply(a.negate()):this.negate().multiply(a).negate();if(a.isNegative())return this.multiply(a.negate()).negate();if(this.lessThan(TWO_PWR_24)&&
a.lessThan(TWO_PWR_24))return DXLong.fromNumber(this.toNumber()*a.toNumber(),this.unsigned);var b=this.high>>>16,c=this.high&65535,d=this.low>>>16,e=this.low&65535,f=a.high>>>16,g=a.high&65535,h=a.low>>>16;a=a.low&65535;var l=e*a;var k=(l>>>16)+d*a;var m=k>>>16;k=(k&65535)+e*h;m+=k>>>16;m+=c*a;var n=m>>>16;m=(m&65535)+d*h;n+=m>>>16;m=(m&65535)+e*g;n=n+(m>>>16)+(b*a+c*h+d*g+e*f)&65535;return DXLong.fromBits((k&65535)<<16|l&65535,n<<16|m&65535,this.unsigned)};
DXLong.prototype.div=function(a){DXLong.isDXLong(a)||(a=DXLong.fromValue(a));if(a.isZero())throw Error("division by zero");if(this.isZero())return this.unsigned?DXLong.UZERO:DXLong.ZERO;var b;if(this.equals(DXLong.MIN_VALUE)){if(a.equals(DXLong.ONE)||a.equals(DXLong.NEG_ONE))return DXLong.MIN_VALUE;if(a.equals(DXLong.MIN_VALUE))return DXLong.ONE;var c=this.shiftRight(1).div(a).shiftLeft(1);if(c.equals(DXLong.ZERO))return a.isNegative()?DXLong.ONE:DXLong.NEG_ONE;var d=this.subtract(a.multiply(c));
return b=c.add(d.div(a))}if(a.equals(DXLong.MIN_VALUE))return this.unsigned?DXLong.UZERO:DXLong.ZERO;if(this.isNegative())return a.isNegative()?this.negate().div(a.negate()):this.negate().div(a).negate();if(a.isNegative())return this.div(a.negate()).negate();b=DXLong.ZERO;for(d=this;d.greaterThanOrEqual(a);){c=Math.max(1,Math.floor(d.toNumber()/a.toNumber()));var e=Math.ceil(Math.log(c)/Math.LN2);e=48>=e?1:Math.pow(2,e-48);for(var f=DXLong.fromNumber(c),g=f.multiply(a);g.isNegative()||g.greaterThan(d);)c-=
e,f=DXLong.fromNumber(c,this.unsigned),g=f.multiply(a);f.isZero()&&(f=DXLong.ONE);b=b.add(f);d=d.subtract(g)}return b};DXLong.prototype.not=function(){return DXLong.fromBits(~this.low,~this.high,this.unsigned)};DXLong.prototype.shiftLeft=function(a){DXLong.isDXLong(a)&&(a=a.toInt());return 0===(a&=63)?this:32>a?DXLong.fromBits(this.low<<a,this.high<<a|this.low>>>32-a,this.unsigned):DXLong.fromBits(0,this.low<<a-32,this.unsigned)};
DXLong.prototype.shiftRight=function(a){DXLong.isDXLong(a)&&(a=a.toInt());return 0===(a&=63)?this:32>a?DXLong.fromBits(this.low>>>a|this.high<<32-a,this.high>>a,this.unsigned):DXLong.fromBits(this.high>>a-32,0<=this.high?0:-1,this.unsigned)};b64map="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";
_base64={encode:function(a){var b="",c=0;do{var d=a.charCodeAt(c++),e=a.charCodeAt(c++),f=a.charCodeAt(c++);d=d?d:0;e=e?e:0;f=f?f:0;var g=d>>2&63;d=(d&3)<<4|e>>4&15;var h=(e&15)<<2|f>>6&3,l=f&63;e?f||(l=64):h=l=64;b+=b64map.charAt(g)+b64map.charAt(d)+b64map.charAt(h)+b64map.charAt(l)}while(c<a.length);return b},decode:function(a){var b="",c=0;do{var d=b64map.indexOf(a.charAt(c++)),e=b64map.indexOf(a.charAt(c++)),f=b64map.indexOf(a.charAt(c++)),g=b64map.indexOf(a.charAt(c++)),h=(e&15)<<4|f>>2&15;f=
(f&3)<<6|g&63;b+=String.fromCharCode((d&63)<<2|e>>4&3)+(h?String.fromCharCode(h):"")+(f?String.fromCharCode(f):"")}while(c<a.length);return b}};function utf16to8(a){var b;var c="";var d=a.length;for(b=0;b<d;b++){var e=a.charCodeAt(b);1<=e&&127>=e?c+=a.charAt(b):(2047<e?(c+=String.fromCharCode(224|e>>12&15),c+=String.fromCharCode(128|e>>6&63)):c+=String.fromCharCode(192|e>>6&31),c+=String.fromCharCode(128|e>>0&63))}return c}
function utf8to16(a){var b;var c="";var d=a.length;for(b=0;b<d;){var e=a.charCodeAt(b++);switch(e>>4){case 0:case 1:case 2:case 3:case 4:case 5:case 6:case 7:c+=a.charAt(b-1);break;case 12:case 13:var f=a.charCodeAt(b++);c+=String.fromCharCode((e&31)<<6|f&63);break;case 14:f=a.charCodeAt(b++);var g=a.charCodeAt(b++);c+=String.fromCharCode((e&15)<<12|(f&63)<<6|(g&63)<<0)}}return c}function int2char(a){return"0123456789abcdefghijklmnopqrstuvwxyz".charAt(a)}
function b64tohex(a){var b="",c,d=0;for(c=0;c<a.length&&"="!=a.charAt(c);++c){var e=b64map.indexOf(a.charAt(c));if(!(0>e))if(0==d){b+=int2char(e>>2);var f=e&3;d=1}else 1==d?(b+=int2char(f<<2|e>>4),f=e&15,d=2):2==d?(b+=int2char(f),b+=int2char(e>>2),f=e&3,d=3):(b+=int2char(f<<2|e>>4),b+=int2char(e&15),d=0)}1==d&&(b+=int2char(f<<2));return b}function b64toBA(a){a=b64tohex(a);var b,c=[];for(b=0;2*b<a.length;++b)c[b]=parseInt(a.substring(2*b,2*b+2),16);return c}
base64={encode:function(a){return _base64.encode(utf16to8(a))},decode:function(a){return utf8to16(_base64.decode(a))},BAtob64:function(a){var b,c=a.length,d="";if(a.get)for(b=0;b<c;b+=3)a.get(b),d+=b64map[a.get(b)>>2],d+=b64map[(a.get(b)&3)<<4|a.get(b+1)>>4],d+=b64map[(a.get(b+1)&15)<<2|a.get(b+2)>>6],d+=b64map[a.get(b+2)&63];else for(b=0;b<c;b+=3)d+=b64map[a[b]>>2],d+=b64map[(a[b]&3)<<4|a[b+1]>>4],d+=b64map[(a[b+1]&15)<<2|a[b+2]>>6],d+=b64map[a[b+2]&63];2===c%3?d=d.substring(0,d.length-1)+"=":1===
c%3&&(d=d.substring(0,d.length-2)+"==");return d},b64toBA:function(a){return new Uint8Array(b64toBA(a))}};
function checkClient(){var a={ie:0,firefox:0,safari:0,opera:0,chrome:0,ver:null,name:name},b={name:""},c=window.navigator.userAgent;window.opera?a.name="opera":/AppleWebKit\/(\S+)/.test(c)?/Chrome\/(\S+)/.test(c)?(a.ver=RegExp.$1,a.name="chrome"):/Version\/(\S+)/.test(c)&&(a.ver=RegExp.$1,a.name="safari"):/rv:([^\)]+)\) Gecko\/\d(8)/.test(c)?(a.ver=RegExp.$1,/Firefox\/(\S+)/.test(c)&&(a.ver=RegExp.$1,a.name="firefox")):/MSIE ([^;]+)/.test(c)&&(a.ver=RegExp.$1,a.name="ie");b.name=0==window.navigator.platform.indexOf("Win")?
"win":"mac";return{browser:a,system:b}}var OFFSET=18E4,deltaT=0,lastCts=0;function init(){watt.on("SyncSrvTimestamp",function(a){var b=(new Date).getTime(),c=parseInt(a.client_tsms,10),d=b-c;5E3<Math.abs(d)?console.warn("rtt bigger:",d):(a=parseInt(a.server_tsms,10)-(b+c)/2,deltaT=Math.floor(a))})}function get(){var a=(new Date).getTime()+deltaT;lastCts-OFFSET<a&&a<lastCts&&(a=lastCts+1);return lastCts=a}
var uuid={k1:Array(32),k2:Array(32),l:4,v:[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],ELEMENTS:"0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ",length:62,prefix:"",init:function(){for(var a=0;a<k1.length;a++)k1[a]=k2[a]=a;for(a=0;a<k1.length;a++)k1[a]=6173*Math.random()%k1.length;for(a=k2.length-1;0<=a;a--){var b=6173*Math.random()%k2.length,c=k2[a];k2[a]=k2[b];k2[b]=c}a=(new Date).getTime()/1E3%1E8;do prefix=ELEMENTS.charAt(a%length)+prefix,a/=length;while(a>=length)},inc:function(a){a>=
this.l&&++this.l;this.v[a]+=1;this.v[a]>=this.ELEMENTS.length&&(this.v[a]=0,inc(this.p+1))},next:function(){this.inc(0);var a=6173*Math.random()%this.ELEMENTS.length,b=""+this.ELEMENTS.charAt(a);a=this.k2[a%this.k2.length]^a>>>1^a<<9;a=this.k1[a%this.k1.length]^a>>>1^a<<8;a=this.k2[a%this.k2.length]^a>>>1^a<<7;for(var c=0;c<this.l;c++){var d=this.v[c];d=(d+this.k1[Math.abs(a)%this.k1.length])%this.ELEMENTS.length;b+=this.ELEMENTS.charAt(d);a=this.k2[d%this.k2.length]^a>>>1^a<<9}return prefix+b}},
ts=Object.prototype.toString,hasLog=!0,MTIM={apply:function(a,b){if(a&&b&&"object"==typeof b)for(var c in b)"undefined"!=typeof b[c]&&(a[c]=b[c]);return a},setLogInfo:function(a,b){!1===b&&(hasLog=!1);var c=a.did||uuid.next();a.did=c;this.opts=extend({dtk:"",ai:1,did:"",dt:deviceInfo.deviceType,av:a.version,env:"online",an:""},a)},_sendLog:function(a,b,c){if(hasLog){var d=checkClient();a=extend({did:"",dtk:"",ai:"",sv:packageJson.version,pt:2===deviceInfo.deviceType?"web":"pc",av:a.version,an:"daxiang",
pv:d.browser.ver,dm:d.browser.name,manuf:d.system.name,events:[b]},this.opts,a);ajax({url:c,headers:{"content-type":"application/json"},processData:!1,data:JSON.stringify(a),dataType:"json",method:"POST"})}},sendLog:function(a,b){MTIM._sendLog(a,b,"https://dxw.sankuai.com/events/api/sdk/v1/xm")},sendLogBody:function(a,b){MTIM._sendLog(a,b,"https://dxw.sankuai.com/events/api/error/v1/packet")},override:function(a,b){this.apply(a.prototype,b)},extend:function(){var a=function(a){for(var b in a)this[b]=
a[b]},b=Object.prototype.constructor;return function(c,d){var e=function(){c.apply(this,arguments)},f=function(){},g=c.prototype;f.prototype=g;f=e.prototype=new f;f.constructor=e;e.superclass=g;g.constructor==b&&(g.constructor=c);e.override=function(a){MTIM.override(e,a)};f.supr=function(){return g};f.override=a;MTIM.override(e,d);return e}}(),isFunction:function(a){return"[object Function]"===ts.apply(a)},isObject:function(a){return"[object Object]"===ts.apply(a)},isEmpty:function(a){return null===
a||void 0===a||""===a},isArray:function(){return Array.isArray||function(a){"[object Array]"===ts.apply(a)}}()},ctsTimer={init:function(){watt.on("SyncSrvTimestamp",function(a){var b=(new Date).getTime(),c=parseInt(a.client_tsms,10),d=b-c;5E3<Math.abs(d)?console.warn("rtt bigger:",d):(a=parseInt(a.server_tsms,10)-(b+c)/2,deltaT=Math.floor(a))})},get:function(){var a=(new Date).getTime()+deltaT;lastCts-OFFSET<a&&a<lastCts&&(a=lastCts+1);return lastCts=a}},MTDX=MTIM,Packet=function(a){this.bufferInited=
!1;this._capacity=constant.PROTO_PACKET_SIZE;this._position=constant.PACKET_HEAD_LENGTH;this.fromUnmarshall=!1;this.init();MTDX.apply(this,a);this.initAfter()};
Packet.prototype={appid:constant.APPID_XMAPP,init:function(){},initAfter:function(){},initBuffer:function(){this.buffer=new ByteBuffer(this._capacity);this.buffer.position(this._position);return!0},release:function(){this.buffer=null},setUri:function(a){this.uri=a},clear:function(){},copy:function(){},snapshotBytes:function(){return this.buffer.snapshot?this.buffer.snapshot:this.getBytes()},setUid:function(a){},getBytes:function(){this._marshall();return this.buffer.getBytes()},getArray:function(){this._marshall();
return this.buffer.getArray()},__byteArr:[],serialize:function(){this.__byteArr=[];for(var a=this.getArray(),b=0;b<a.length;b++)this.__byteArr.push(a[b]);return JSON.stringify(this.__byteArr)},unserialize:function(){return this},getBase64:function(){return base64.BAtob64(this.getArray())},_marshall:function(){this.bufferInited||(this.bufferInited=this.initBuffer());this.marshall();var a=this.buffer.position();this.buffer.putInt(a,0);this.buffer.putInt(this.uri,4);this.buffer.putShort(this.appid,8)},
toPure:function(){delete this._capacity;delete this._position;delete this.buffer;delete this.fromUnmarshall;delete this.bufferInited},parserFromBuffer:function(a){this._unmarshall(a);return this},fromBuffer:function(a){this._unmarshall(a);return this},_unmarshall:function(a){this.fromUnmarshall=!0;this.buffer=ByteBuffer.wrap(a);this.length=this.popInt();this.uri=this.popInt();this.appid=this.popShort();try{this.unmarshall()}catch(b){console.log(b)}},_pushBool:function(a){this.buffer.writeByte(a?1:
0)},popBool:function(){return 1==this.popByte()?!0:!1},_pushByte:function(a){this.buffer.writeByte(a)},popByte:function(){return this.buffer.readByte()},_pushShort:function(a){this.buffer.putShort(a)},popShort:function(){return this.buffer.popShort()},_pushInt:function(a){this.buffer.putInt(a||0)},popInt:function(){return this.buffer.popInt()},_pushDouble:function(a){this.buffer.putDouble(a||0)},popDouble:function(){return this.buffer.popDouble()},popDXLong:function(){return this.buffer.popDXLong()},
_pushDXLong:function(a){return this.buffer.putDXLong(a||0)},_pushString:function(a){a?(a=this.buffer.writeUTF8String(a,this.buffer.writeOffset+2),this._pushShort(a),this.buffer.position(this.buffer.writeOffset+a)):this._pushShort(0)},_pushArrayDXLong:function(a){if(a){var b=a.length;this._pushShort(b);for(var c=0;c<b;c++)this._pushDXLong(a[c])}else this._pushShort(0)},popString:function(){return this.buffer.readUTF8String(this.buffer.popShort())},_pushArrayArray:function(a){if(a){var b=a.length;this._pushShort(b);
for(var c=0;c<b;c++)a[c]instanceof Packet?this._pushPacket(a[c]):this._pushBytes(a[c])}else this._pushShort(0)},_popArrayArray:function(){for(var a=this.buffer.popShort(),b=[],c=0;c<a;c++)b[c]=this.popBytes();return b},_popArrayDXLong:function(){for(var a=this.buffer.popShort(),b=[],c=0;c<a;c++)b[c]=this.popDXLong().value();return b},_pushBytes:function(a){a&&a.byteLength?(this.buffer.putShort(a.byteLength),this.buffer.putBytes(a)):this.buffer.putShort(0)},popBytes:function(){return this.buffer.popBytes(this.buffer.popShort())},
popMapOfShortAndInt:function(){for(var a={},b=this.buffer.popShort(),c=0;c<b;c++){var d=this.buffer.popShort(),e=this.buffer.popInt();a[d]=e}return a},popMapOfDXLongAndByte:function(){for(var a={},b=this.buffer.popShort(),c=0;c<b;c++){var d=this.buffer.popDXLong(),e=this.popByte();a[d]=e}return a},popUItem:function(){var a={};a.uid=this.popDXLong().value();a.appId=this.popShort();return a},_pushPacket:function(a){a&&this._pushBytes(a.getBytes())},push:function(a,b){"undefined"===typeof b&&("string"==
typeof a?b=bt.STRING:"number"==typeof a?b=bt.INT:a instanceof Packet?b=bt.PACKET:DXLong.isDXLong(a)?b=bt.LONG:MTDX.isArray(a)&&(b=bt.ARRAY_LONG));switch(b){case bt.INT:this._pushInt(a);break;case bt.SHORT:this._pushShort(a);break;case bt.LONG:this._pushDXLong(a);break;case bt.STRING:this._pushString(a);break;case bt.BOOLEAN:this._pushBool(a);break;case bt.BYTE:this._pushByte(a);break;case bt.BYTES:this._pushBytes(a);break;case bt.PACKET:this._pushPacket(a);break;case bt.ARRAY_LONG:this._pushArrayDXLong(a);
break;case bt.ARRAY_ARRAY:this._pushArrayArray(a);break;default:throw Error("Unsupported data type: "+b);}return this},getCts:ctsTimer.get};var has=Object.prototype.hasOwnProperty,prefix="function"!==typeof Object.create?"~":!1;function EE(a,b,c){this.fn=a;this.context=b;this.once=c||!1}function EventEmitter(){}EventEmitter.prototype._events=void 0;
EventEmitter.prototype.eventNames=function(){var a=this._events,b=[],c;if(!a)return b;for(c in a)has.call(a,c)&&b.push(prefix?c.slice(1):c);return Object.getOwnPropertySymbols?b.concat(Object.getOwnPropertySymbols(a)):b};EventEmitter.prototype.listeners=function(a,b){var c=prefix?prefix+a:a;c=this._events&&this._events[c];if(b)return!!c;if(!c)return[];if(c.fn)return[c.fn];for(var d=0,e=c.length,f=Array(e);d<e;d++)f[d]=c[d].fn;return f};
EventEmitter.prototype.emit=function(a,b,c,d,e,f){var g=prefix?prefix+a:a;if(!this._events||!this._events[g])return!1;g=this._events[g];var h=arguments.length,l;if("function"===typeof g.fn){g.once&&this.removeListener(a,g.fn,void 0,!0);switch(h){case 1:return g.fn.call(g.context),!0;case 2:return g.fn.call(g.context,b),!0;case 3:return g.fn.call(g.context,b,c),!0;case 4:return g.fn.call(g.context,b,c,d),!0;case 5:return g.fn.call(g.context,b,c,d,e),!0;case 6:return g.fn.call(g.context,b,c,d,e,f),
!0}var k=1;for(l=Array(h-1);k<h;k++)l[k-1]=arguments[k];g.fn.apply(g.context,l)}else{var m=g.length;for(k=0;k<m;k++)switch(g[k].once&&this.removeListener(a,g[k].fn,void 0,!0),h){case 1:g[k].fn.call(g[k].context);break;case 2:g[k].fn.call(g[k].context,b);break;case 3:g[k].fn.call(g[k].context,b,c);break;default:if(!l){var n=1;for(l=Array(h-1);n<h;n++)l[n-1]=arguments[n]}g[k].fn.apply(g[k].context,l)}}return!0};
EventEmitter.prototype.on=function(a,b,c){b=new EE(b,c||this);a=prefix?prefix+a:a;this._events||(this._events=prefix?{}:Object.create(null));this._events[a]?this._events[a].fn?this._events[a]=[this._events[a],b]:this._events[a].push(b):this._events[a]=b;return this};
EventEmitter.prototype.once=function(a,b,c){b=new EE(b,c||this,!0);a=prefix?prefix+a:a;this._events||(this._events=prefix?{}:Object.create(null));this._events[a]?this._events[a].fn?this._events[a]=[this._events[a],b]:this._events[a].push(b):this._events[a]=b;return this};
EventEmitter.prototype.removeListener=function(a,b,c,d){a=prefix?prefix+a:a;if(!this._events||!this._events[a])return this;var e=this._events[a],f=[];if(b)if(e.fn)(e.fn!==b||d&&!e.once||c&&e.context!==c)&&f.push(e);else for(var g=0,h=e.length;g<h;g++)(e[g].fn!==b||d&&!e[g].once||c&&e[g].context!==c)&&f.push(e[g]);f.length?this._events[a]=1===f.length?f[0]:f:delete this._events[a];return this};
EventEmitter.prototype.removeAllListeners=function(a){if(!this._events)return this;a?delete this._events[prefix?prefix+a:a]:this._events=prefix?{}:Object.create(null);return this};EventEmitter.prototype.off=EventEmitter.prototype.removeListener;EventEmitter.prototype.addListener=EventEmitter.prototype.on;EventEmitter.prototype.setMaxListeners=function(){return this};EventEmitter.prefixed=prefix;var watt=new EventEmitter;Protocol={};
var mustImpl=function(a){if("undefined"===typeof this[a])throw Error("["+a+"] is required~");};Protocol.Request=MTIM.extend(Packet,{});Protocol.Request.extend=function(a){mustImpl.call(a,"init");mustImpl.call(a,"marshall");return MTIM.extend(Protocol.Request,a)};
var packetMap={},packUp=function(a,b){if("number"==typeof a)packetMap[a]=b;else for(var c=0;c<a.length;c++)packetMap[a[c]]=b;return b},getHeader=function(a){return{length:a[3]+(a[2]<<8)+(a[1]<<16)+(a[0]<<24),uri:a[7]+(a[6]<<8)+(a[5]<<16)+(a[4]<<24),appid:a[9]+(a[8]<<8),buffer:{array:a}}},unmarshall=function(a,b,c){a=ByteBuffer.wrap(a);var d=getHeader(a.array),e=packetMap[d.uri];if(e)try{return(new e).fromBuffer(a)}catch(f){if(MTIM.sendLog({},{nm:"umer",val:{value1:d.uri},ts:+new Date}),c)throw Error();
}return MTIM.apply(b||{},d)};Protocol.TransUp=MTIM.extend(Packet,{uri:constant.URI_UNI_TRANSUP,init:function(){this.uid=this.svid=0;this.buf=null},marshall:function(){this.push(this.svid,bt.SHORT);this.push(this.uid,bt.LONG);this.push(this.buf,bt.BYTES)},unmarshall:function(){this.svid=this.popShort();this.uid=this.popDXLong().value();this.buf=this.popBytes()},unserialize:function(){return unmarshall(this.buf)}});packUp(constant.URI_UNI_TRANSUP,Protocol.TransUp);
Protocol.Response=MTIM.extend(Packet,{toPure:function(){Protocol.Response.superclass.toPure.call(this);this.message&&this.message.toPure&&this.message.toPure();this.msgId&&(this.msgId=this.msgId.value?this.msgId.value():this.msgId);return this}});Protocol.Response.extend=function(a){mustImpl.call(a,"uri");mustImpl.call(a,"unmarshall");return packUp(a.uri,MTIM.extend(Protocol.Response,a))};Protocol.Response.fromBuffer=function(a){return unmarshall(a,{text:"unknown response type",type:-1})};
Protocol.Response.fromBase64=function(a){return Protocol.Response.fromBuffer(base64.b64toBA(a).buffer)};Protocol.Message=MTIM.extend(Packet,{toPure:function(){Protocol.Message.superclass.toPure.call(this);return this}});Protocol.Message.extend=function(a){mustImpl.call(a,"init");mustImpl.call(a,"marshall");mustImpl.call(a,"unmarshall");return packUp(a.uri,MTIM.extend(Protocol.Message,a))};Protocol.Message.fromBuffer=function(a){return unmarshall(a,{text:"unknown message type",type:-1},!0)};
watt.on("_dataRecv",function(a){a=unmarshall(a,{text:"unknown data type",type:-1});watt.emit(a.uri,a)});var Protocol={};mustImpl=function(a){if("undefined"===typeof this[a])throw Error("["+a+"] is required~");};Protocol.Request=MTIM.extend(Packet,{});Protocol.Request.extend=function(a){mustImpl.call(a,"init");mustImpl.call(a,"marshall");return MTIM.extend(Protocol.Request,a)};packetMap={};packUp=function(a,b){if("number"==typeof a)packetMap[a]=b;else for(var c=0;c<a.length;c++)packetMap[a[c]]=b;return b};
getHeader=function(a){return{length:a[3]+(a[2]<<8)+(a[1]<<16)+(a[0]<<24),uri:a[7]+(a[6]<<8)+(a[5]<<16)+(a[4]<<24),appid:a[9]+(a[8]<<8),buffer:{array:a}}};unmarshall=function(a,b,c){a=ByteBuffer.wrap(a);var d=getHeader(a.array),e=packetMap[d.uri];if(e)try{return(new e).fromBuffer(a)}catch(f){if(console.log(f),MTIM.sendLog({},{nm:"umer",val:{value1:d.uri},ts:+new Date}),c)throw Error();}return MTIM.apply(b||{},d)};
Protocol.TransUp=MTIM.extend(Packet,{uri:constant.URI_UNI_TRANSUP,init:function(){this.uid=this.svid=0;this.buf=null},marshall:function(){this.push(this.svid,bt.SHORT);this.push(this.uid,bt.LONG);this.push(this.buf,bt.BYTES)},unmarshall:function(){this.svid=this.popShort();this.uid=this.popDXLong().value();this.buf=this.popBytes()},unserialize:function(){return unmarshall(this.buf)}});packUp(constant.URI_UNI_TRANSUP,Protocol.TransUp);
Protocol.Response=MTIM.extend(Packet,{toPure:function(){Protocol.Response.superclass.toPure.call(this);this.message&&this.message.toPure&&this.message.toPure();this.msgId&&(this.msgId=this.msgId.value?this.msgId.value():this.msgId);return this}});Protocol.Response.extend=function(a){mustImpl.call(a,"uri");mustImpl.call(a,"unmarshall");return packUp(a.uri,MTIM.extend(Protocol.Response,a))};Protocol.Response.fromBuffer=function(a){return unmarshall(a,{text:"unknown response type",type:-1})};
Protocol.Response.fromBase64=function(a){return Protocol.Response.fromBuffer(base64.b64toBA(a).buffer)};Protocol.Message=MTIM.extend(Packet,{toPure:function(){Protocol.Message.superclass.toPure.call(this);return this}});Protocol.Message.extend=function(a){mustImpl.call(a,"init");mustImpl.call(a,"marshall");mustImpl.call(a,"unmarshall");return packUp(a.uri,MTIM.extend(Protocol.Message,a))};Protocol.Message.fromBuffer=function(a){return unmarshall(a,{text:"unknown message type",type:-1},!0)};
watt.on("_dataRecv",function(a){a=unmarshall(a,{text:"unknown data type",type:-1});watt.emit(a.uri,a)});
var utfx=function(){var a={encodeUTF8:function(a,c){var b=null;"number"===typeof a&&(b=a,a=function(){return null});for(;null!==b||null!==(b=a());)128>b?c(b&127):(2048>b?c(b>>6&31|192):(65536>b?c(b>>12&15|224):(c(b>>18&7|240),c(b>>12&63|128)),c(b>>6&63|128)),c(b&63|128)),b=null},decodeUTF8:function(a,c){for(var b,e,f,g,h=function(a){a=a.slice(0,a.indexOf(null));var b=Error(a.toString());b.name="TruncatedError";b.bytes=a;throw b;};null!==(b=a());)if(0===(b&128))c(b);else if(192===(b&224))null===(e=
a())&&h([b,e]),c((b&31)<<6|e&63);else if(224===(b&240))null!==(e=a())&&null!==(f=a())||h([b,e,f]),c((b&15)<<12|(e&63)<<6|f&63);else if(240===(b&248))null!==(e=a())&&null!==(f=a())&&null!==(g=a())||h([b,e,f,g]),c((b&7)<<18|(e&63)<<12|(f&63)<<6|g&63);else throw RangeError("Illegal starting byte: "+b);},UTF16toUTF8:function(a,c){for(var b,e=null;null!==(b=null!==e?e:a());)55296<=b&&57343>=b&&null!==(e=a())&&56320<=e&&57343>=e?(c(1024*(b-55296)+e-56320+65536),e=null):c(b);null!==e&&c(e)},UTF8toUTF16:function(a,
c){var b=null;"number"===typeof a&&(b=a,a=function(){return null});for(;null!==b||null!==(b=a());)65535>=b?c(b):(b-=65536,c((b>>10)+55296),c(b%1024+56320)),b=null},encodeUTF16toUTF8:function(b,c){a.UTF16toUTF8(b,function(b){a.encodeUTF8(b,c)})},decodeUTF8toUTF16:function(b,c){a.decodeUTF8(b,function(b){a.UTF8toUTF16(b,c)})},calculateCodePoint:function(a){return 128>a?1:2048>a?2:65536>a?3:4},calculateUTF8:function(b){for(var c,d=0;null!==(c=b());)d+=a.calculateCodePoint(c);return d},calculateUTF16asUTF8:function(b){var c=
0,d=0;a.UTF16toUTF8(b,function(b){++c;d+=a.calculateCodePoint(b)});return[c,d]}};return a}(),stringFromCharCode=String.fromCharCode;ts=Object.prototype.toString;function stringSource(a){var b=0;return function(){return b<a.length?a.charCodeAt(b++):null}}
function stringDestination(){var a=[],b=[];return function(){if(0===arguments.length)return b.join("")+stringFromCharCode.apply(String,a);1024<a.length+arguments.length&&(b.push(stringFromCharCode.apply(String,a)),a.length=0);Array.prototype.push.apply(a,arguments)}}
var ByteBuffer=function(a,b){"number"==typeof a?(this.capacity=a,this.buffer=new ArrayBuffer(this.capacity)):"object"==typeof a&&(this.capacity=a.byteLength,this.buffer=a);this.array=new Uint8Array(this.buffer);this.view=new DataView(this.buffer);this.readOffset=this.writeOffset=0;this.snapshot=null;this.littleEndian=!!b};ByteBuffer.METRICS_CHARS="c";ByteBuffer.METRICS_BYTES="b";
ByteBuffer.wrap=function(a){return"[object ArrayBuffer]"===ts.apply(a)?new ByteBuffer(a):"[object Array]"===ts.apply(a)?new ByteBuffer((new Uint8Array(a)).buffer):a instanceof ByteBuffer?a:new ByteBuffer(a)};ByteBuffer.strToBytes=function(a){if(null==a||""==a)return new ArrayBuffer(0);var b=new ByteBuffer(3*a.length);b.writeUTF8String(a);return b.getBytes()};
ByteBuffer.prototype={putShort:function(a,b){var c="undefined"===typeof b;c&&(b=this.writeOffset);b+=2;var d=this.buffer.byteLength;b>d&&this.resize((d*=2)>b?d:b);this.view.setUint16(b-2,a,this.littleEndian);c&&(this.writeOffset+=2);return this},popShort:function(a){var b="undefined"===typeof a;b&&(a=this.readOffset);if(a>=this.capacity)return null;a=this.view.getUint16(a,this.littleEndian);b&&(this.readOffset+=2);return a},putInt:function(a,b){var c="undefined"===typeof b;c&&(b=this.writeOffset);
b+=4;var d=this.buffer.byteLength;b>d&&this.resize((d*=2)>b?d:b);this.view.setUint32(b-4,a,this.littleEndian);c&&(this.writeOffset+=4);return this},popInt:function(a){var b="undefined"===typeof a;b&&(a=this.readOffset);if(a>=this.capacity)return null;a=this.view.getUint32(a,this.littleEndian);b&&(this.readOffset+=4);return a},readByte:function(a){var b="undefined"===typeof a;b&&(a=this.readOffset);if(a>=this.capacity)return null;a=this.view.getUint8(a);b&&(this.readOffset+=1);return a},writeByte:function(a,
b){var c="undefined"===typeof b;c&&(b=this.writeOffset);b+=1;var d=this.buffer.byteLength;b>d&&this.resize((d*=2)>b?d:b);this.view.setUint8(b-1,a);c&&(this.writeOffset+=1);return this},putBytes:function(a,b){for(var c=new DataView(a),d=0;d<a.byteLength;d++)this.writeByte(c.getUint8(d));return this},popBytes:function(a,b){for(var c=new ArrayBuffer(a),d=new DataView(c),e=0;e<a;e++)d.setUint8(e,this.readByte());return c},putDXLong:function(a,b){var c=DXLong.fromValue(a,!0);"number"===typeof b?this.putInt(c.high,
b).putInt(c.low,b+4):this.putInt(c.high).putInt(c.low);return this},popDXLong:function(a){if("number"===typeof a){var b=this.popInt(a);a=this.popInt(a+4)}else b=this.popInt(),a=this.popInt();return DXLong.fromBits(a,b,!0)},putDouble:function(a,b){var c="undefined"===typeof b;c&&(b=this.writeOffset);b+=8;var d=this.buffer.byteLength;b>d&&this.resize((d*=2)>b?d:b);this.view.setFloat64(b-8,a,this.littleEndian);c&&(this.writeOffset+=8);return this},popDouble:function(a){var b="undefined"===typeof a;b&&
(a=this.readOffset);if(a>=this.capacity)return null;a=this.view.getFloat64(a,this.littleEndian);b&&(this.readOffset+=8);return a},writeUTF8String:function(a,b){var c="undefined"===typeof b;c&&(b=this.writeOffset);var d=b;var e=utfx.calculateUTF16asUTF8(stringSource(a))[1];b+=e;var f=this.buffer.byteLength;b>f&&this.resize((f*=2)>b?f:b);b-=e;utfx.encodeUTF16toUTF8(stringSource(a),function(a){this.view.setUint8(b++,a)}.bind(this));c&&(this.writeOffset=b);return b-d},readUTF8String:function(a,b,c){"number"===
typeof b&&(c=b,b=void 0);var d="undefined"===typeof c;d&&(c=this.readOffset);if(c>this.capacity)return null;"undefined"===typeof b&&(b=ByteBuffer.METRICS_BYTES);var e=0,f=c;if(b===ByteBuffer.METRICS_CHARS){var g=stringDestination();utfx.decodeUTF8(function(){return e<a&&c<this.capacity?this.view.getUint8(c++):null}.bind(this),function(a){++e;utfx.UTF8toUTF16(a,g)}.bind(this));if(e!==a)throw RangeError("Illegal range: Truncated data, "+e+" == "+a);return d?(this.readOffset=c,g()):{string:g(),length:c-
f}}if(b===ByteBuffer.METRICS_BYTES){var h=c+a;utfx.decodeUTF8toUTF16(function(){return c<h?this.view.getUint8(c++):null}.bind(this),g=stringDestination());if(c!==h)throw RangeError("Illegal range: Truncated data, "+c+" == "+h);return d?(this.readOffset=c,g()):{string:g(),length:c-f}}throw TypeError("Unsupported metrics: "+b);},resize:function(a){if(this.buffer.byteLength<a){var b=new ArrayBuffer(a);(new Uint8Array(b)).set(new Uint8Array(this.buffer));this.buffer=b;this.view=new DataView(this.buffer);
this.array=new Uint8Array(this.buffer);this.capacity=a}return this},position:function(a){if("number"==typeof a)this.writeOffset=a;else return this.writeOffset},getBytes:function(){this.snapshot=new ArrayBuffer(this.writeOffset);(new Uint8Array(this.snapshot)).set(this.array.subarray(0,this.writeOffset));return this.snapshot},getArray:function(){return this.array.subarray(0,this.writeOffset)}};var httpSession={};
httpSession.MsgHistoryRes=Protocol.Response.extend({uri:constant.HTTP.URI_MSG_HISTORY_RES,init:function(){this.uid=0;this.msgs=[];this.requestId=this.rescode=this.next=0},marshall:function(){this.push(this.uid,bt.LONG);this.push(this.msgs,bt.ARRAY_ARRAY);this.push(this.next);this.push(this.rescode);this.push(this.requestId,bt.LONG)},unmarshall:function(){this.uid=this.popDXLong().value();for(var a=this._popArrayArray(),b=0;b<a.length;b++)0<a[b].byteLength&&this.msgs.push(Protocol.Response.fromBuffer(a[b]));
this.next=this.popInt();this.rescode=this.popInt();this.requestId=this.popDXLong().value()}});
httpSession.MsgChatListRes=Protocol.Response.extend({uri:constant.HTTP.URI_MSG_CHATLIST_RES,init:function(){this.uid=0;this.chats=[];this.requestId=this.rescode=this.next=0},marshall:function(){this.push(this.uid,bt.LONG);this.push(this.chats,bt.ARRAY_ARRAY);this.push(this.next);this.push(this.rescode);this.push(this.requestId,bt.LONG)},unmarshall:function(){this.uid=this.popDXLong().value();for(var a=this._popArrayArray(),b=0;b<a.length;b++)0<a[b].byteLength&&this.chats.push(Protocol.Response.fromBuffer(a[b]));
this.next=this.popInt();this.rescode=this.popInt();this.requestId=this.popDXLong().value()}});httpSession.fromBase64ToBuffer=function(a,b){return(new b).parserFromBuffer(base64.b64toBA(a).buffer)};
httpSession.LvsLoginAddr=Protocol.Response.extend({uri:constant.SVID_LVS<<16|11,init:function(){this.ip=[];this.domain=this.port=""},getAddr:function(){var a="https:"===location.protocol?"wss://":"ws://";return this.domain?a+this.domain+":"+this.port:a+this.ip.reverse().join(".")+":"+this.port},unmarshall:function(){this.ip.push(this.popByte());this.ip.push(this.popByte());this.ip.push(this.popByte());this.ip.push(this.popByte());this.port=this.popShort();this.domain=this.popString()}});
var SVID_IM=constant.SVID_IM,imConstant={SVID_IM:SVID_IM,Message:constant.Message,MESSAGE_EVENT:constant.MESSAGE_EVENT,CipherType:constant.CipherType,ChatType:constant.CHAT_TYPE,GENERAL_TYPE:constant.GENERAL_TYPE};
imConstant.IM={URI_IM_SEND_MSG:SVID_IM<<16|1,URI_IM_SEND_MSG_RES:SVID_IM<<16|2,URI_IM_SEND_GROUP_MSG:SVID_IM<<16|3,URI_IM_SEND_GROUP_MSG_RES:SVID_IM<<16|4,URI_IM_ACK_MSG:SVID_IM<<16|5,URI_IM_DELETE_MSG:SVID_IM<<16|7,URI_IM_DELETE_MSG_RES:SVID_IM<<16|8,URI_IM_TEXT_INFO:SVID_IM<<16|9,URI_IM_AUDIO_INFO:SVID_IM<<16|10,URI_IM_VIDEO_INFO:SVID_IM<<16|11,URI_IM_IMAGE_INFO:SVID_IM<<16|12,URI_IM_CALENDAR_INFO:SVID_IM<<16|13,URI_IM_LINK_INFO:SVID_IM<<16|14,URI_IM_MULTI_LINK_INFO:SVID_IM<<16|15,URI_IM_FILE_INFO:SVID_IM<<
16|16,URI_IM_GPS_INFO:SVID_IM<<16|17,URI_IM_VCARD_INFO:SVID_IM<<16|18,URI_IM_EMOTION_INFO:SVID_IM<<16|19,URI_IM_EVENT_INFO:SVID_IM<<16|20,URI_IM_ACK_GROUP_MSGS:SVID_IM<<16|21,URI_IM_ACK_MSGS:SVID_IM<<16|22,URI_IM_SYNC_READ_ITEM:SVID_IM<<16|23,URI_IM_SYNC_READ:SVID_IM<<16|24,URI_IM_SYNC_READ_GET:SVID_IM<<16|25,URI_IM_ACK_SYNC_GROUP_MSGS:SVID_IM<<16|26,URI_IM_ACK_SYNC_MSGS:SVID_IM<<16|27,URI_IM_GROUP_NOTICE:SVID_IM<<16|28,URI_IM_CUSTOM_INFO:SVID_IM<<16|29,URI_IM_CHAT_NOTICE:SVID_IM<<16|30,URI_IM_RECEIPT_MSG_REQ:SVID_IM<<
16|31,URI_IM_RECEIPT_GROUP_MSG_REQ:SVID_IM<<16|32,URI_IM_RECEIPT_MSG_RES:SVID_IM<<16|33,URI_IM_RECEIPT_GROUP_MSG_RES:SVID_IM<<16|34,URI_IM_MARK_READ:SVID_IM<<16|35,URI_IM_MARK_READS:SVID_IM<<16|36,URI_IM_REDPACKET_INFO:SVID_IM<<16|37,URL_IM_GENERAL_INFO:SVID_IM<<16|38,URI_IM_GVCARD_INFO:SVID_IM<<16|39,URI_IM_PCALL_INFO:SVID_IM<<16|40,URI_IM_NEWEMOTION_INFO:SVID_IM<<16|41,URI_IM_OPPOSITE_SYNC2_READ:SVID_IM<<16|44,URI_IM_OPPOSITE_SYNC2_READ_ITEM:SVID_IM<<16|45,URI_IM_OPPOSITE_SYNC2_READ_RES:SVID_IM<<
16|46,URI_IM_CANCEL_MSG:SVID_IM<<16|301,URI_IM_CANCEL_MSG_RES:SVID_IM<<16|302,URI_IM_CANCEL_GROUP_MSG:SVID_IM<<16|303,URI_IM_CANCEL_GROUP_MSG_RES:SVID_IM<<16|304};imConstant.NoticeType={GIM_GINFO_UPDATE:1,GIM_GROUP_GEN:2,GIM_GROUP_DEL:3,GIM_MEMBER_ADD:4,GIM_MEMBER_REMOVE:5,GIM_MEMBER_ROLE:6,GIM_GROUP_NOTICE:13,GIM_GROUP_PERMISSION:14,GIM_NOTICE_READ_STATUS:18,GIM_NOTICE_DELETE:19,GIM_NOTICE_UNREAD_COUNT_CHANGE:20};SVID_IM=constant.SVID_IM;var IMMessage={};
IMMessage.IMTextMessage=Protocol.Message.extend({__category:"IM",__type:imConstant.Message.MSG_TYPE_TEXT,uri:imConstant.IM.URI_IM_TEXT_INFO,init:function(){this.text="";this.font_name="serif";this.font_size=12;this.bold=!1;this.cipher_type=imConstant.CipherType.NO_CIPHER},marshall:function(){this.cipher_type==imConstant.CipherType.BASE64?this.push(base64.encode(this.text)):this.push(this.text);this.push(this.font_name);this.push(this.font_size);this.push(this.bold,bt.BOOLEAN)},unmarshall:function(){this.text=
this.popString();this.font_name=this.popString();this.font_size=this.popInt();this.bold=this.popBool();this.cipher_type==imConstant.CipherType.BASE64&&(this.text=base64.decode(this.text))}});
IMMessage.IMImageMessage=Protocol.Message.extend({__category:"IM",__type:imConstant.Message.MSG_TYPE_IMAGE,uri:imConstant.IM.URI_IM_IMAGE_INFO,init:function(){this.token=this.type=this.original=this.normal=this.thumbnail="";this.originSize=0;this.uploadImageType=2},marshall:function(){this.push(this.thumbnail);this.push(this.normal);this.push(this.original);this.push(this.type);this.push(this.token);this.push(this.originSize);this.push(this.uploadImageType)},unmarshall:function(){this.thumbnail=this.popString();
this.normal=this.popString();this.original=this.popString();this.type=this.popString();this.token=this.popString();this.originSize=this.popInt();this.uploadImageType=this.popByte()}});
IMMessage.IMLinkMessage=Protocol.Message.extend({__category:"IM",__type:imConstant.Message.MSG_TYPE_LINK,uri:imConstant.IM.URI_IM_LINK_INFO,init:function(){this.link=this.content=this.image=this.title=""},marshall:function(){this.push(this.title);this.push(this.image);this.push(this.content);this.push(this.link)},unmarshall:function(){this.title=this.popString();this.image=this.popString();this.content=this.popString();this.link=this.popString()}});
IMMessage.IMMultiLinkMessage=Protocol.Message.extend({__category:"IM",__type:imConstant.Message.MSG_TYPE_MULTI_LINK,uri:imConstant.IM.URI_IM_MULTI_LINK_INFO,init:function(){this.num=0;this.content=""},marshall:function(){this.push(this.num,bt.SHORT);this.push(this.content)},unmarshall:function(){this.num=this.popShort();this.content=this.popString()}});
IMMessage.IMEmotionMessage=Protocol.Message.extend({__category:"IM",__type:imConstant.Message.MSG_TYPE_EMOTION,uri:imConstant.IM.URI_IM_EMOTION_INFO,init:function(){this.name=this.type=this.category=""},marshall:function(){this.push(this.category);this.push(this.type);this.push(this.name)},unmarshall:function(){this.category=this.popString();this.type=this.popString();this.name=this.popString()}});
IMMessage.IMEventMessage=Protocol.Message.extend({__category:"IM",__type:imConstant.Message.MSG_TYPE_EVENT,uri:imConstant.IM.URI_IM_EVENT_INFO,init:function(){this.text=this.type=""},marshall:function(){this.push(this.type);this.push(this.text)},unmarshall:function(){this.type=this.popString();this.text=this.popString()}});
IMMessage.IMCalendarMessage=Protocol.Message.extend({__category:"IM",__type:imConstant.Message.MSG_TYPE_CALENDAR,uri:imConstant.IM.URI_IM_CALENDAR_INFO,init:function(){this.dtend=this.dtstart=0;this.calendarID=this.remark=this.participant=this.trigger=this.location=this.summary=""},marshall:function(){this.push(this.dtstart,bt.LONG);this.push(this.dtend,bt.LONG);this.push(this.summary);this.push(this.location);this.push(this.trigger);this.push(this.participant);this.push(this.remark);this.push(this.calendarID,
bt.LONG)},unmarshall:function(){this.dtstart=this.popDXLong().value();this.dtend=this.popDXLong().value();this.summary=this.popString();this.location=this.popString();this.trigger=this.popString();this.participant=this.popString();this.remark=this.popString();this.calendarID=this.popDXLong().value()}});
IMMessage.IMAudioMessage=Protocol.Message.extend({__category:"IM",__type:imConstant.Message.MSG_TYPE_VOICE,uri:imConstant.IM.URI_IM_AUDIO_INFO,init:function(){this.url="";this.stamp=this.duration=this.codec=0;this.token=""},marshall:function(){this.push(this.url);this.push(this.codec,bt.SHORT);this.push(this.duration,bt.SHORT);this.push(this.stamp,bt.LONG);this.push(this.token)},unmarshall:function(){this.url=this.popString();this.codec=this.popShort();this.duration=this.popShort();this.stamp=this.popDXLong().value();
this.token=this.popString()}});
IMMessage.IMVideoMessage=Protocol.Message.extend({__category:"IM",__type:imConstant.Message.MSG_TYPE_VIDEO,uri:imConstant.IM.URI_IM_VIDEO_INFO,init:function(){this.videoUrl="";this.timestamp=this.height=this.width=this.size=this.duration=this.screenshotUrl=0;this.token=""},marshall:function(){this.push(this.videoUrl);this.push(this.screenshotUrl);this.push(this.duration);this.push(this.size);this.push(this.width,bt.SHORT);this.push(this.height,bt.SHORT);this.push(this.timestamp,bt.LONG);this.push(this.token)},
unmarshall:function(){this.videoUrl=this.popString();this.screenshotUrl=this.popString();this.duration=this.popInt();this.size=this.popInt();this.width=this.popShort();this.height=this.popShort();this.timestamp=this.popDXLong().value();this.token=this.popString()}});
IMMessage.IMGPSMessage=Protocol.Message.extend({__category:"IM",__type:imConstant.Message.MSG_TYPE_GPS,uri:imConstant.IM.URI_IM_GPS_INFO,init:function(){this.longitude=this.latitude=0;this.name=""},marshall:function(){this.push(1E6*this.latitude);this.push(1E6*this.longitude);this.push(this.name)},unmarshall:function(){this.latitude=this.popInt()/1E6;this.longitude=this.popInt()/1E6;this.name=this.popString()}});
IMMessage.IMVCardMessage=Protocol.Message.extend({__category:"IM",__type:imConstant.Message.MSG_TYPE_VCARD,uri:imConstant.IM.URI_IM_VCARD_INFO,init:function(){this.uri=imConstant.IM.URI_IM_VCARD_INFO;this.uid=0;this.account=this.name="";this.subtype=this.type=0},marshall:function(){this.push(this.uid,bt.LONG);this.push(this.name);this.push(this.account);this.push(this.type,bt.SHORT);this.push(this.subtype,bt.SHORT)},unmarshall:function(){this.uid=this.popDXLong().value();this.name=this.popString();
this.account=this.popString();this.type=this.popShort();this.subtype=this.popShort()}});
IMMessage.IMFileMessage=Protocol.Message.extend({__category:"IM",__type:imConstant.Message.MSG_TYPE_FILE,uri:imConstant.IM.URI_IM_FILE_INFO,init:function(){this.format=this.name=this.url=this.id="";this.size=0;this.token=""},marshall:function(){this.push(this.id);this.push(this.url);this.push(this.name);this.push(this.format);this.push(this.size);this.push(this.token)},unmarshall:function(){this.id=this.popString();this.url=this.popString();this.name=this.popString();this.format=this.popString();
this.size=this.popInt();this.token=this.popString()}});
IMMessage.IMCustomInfo=Protocol.Message.extend({__category:"IM",__type:imConstant.Message.MSG_TYPE_CUSTOM,uri:imConstant.IM.URI_IM_CUSTOM_INFO,init:function(){this.linkName=this.content=this.contentTitle=this.templateName="";this.link=0},marshall:function(){this.push(this.templateName);this.push(this.contentTitle);this.push(this.content);this.push(this.linkName);this.push(this.link)},unmarshall:function(){this.templateName=this.popString();this.contentTitle=this.popString();this.content=this.popString();
this.linkName=this.popString();this.link=this.popString()}});IMMessage.IMRedPacketInfo=Protocol.Message.extend({__category:"IM",__type:imConstant.Message.MSG_TYPE_RED_PACKET,uri:imConstant.IM.URI_IM_REDPACKET_INFO,init:function(){this.type=this.rpid=0;this.greetings=""},marshall:function(){this.push(this.rpid,bt.LONG);this.push(this.type,bt.SHORT);this.push(this.greetings,bt.STRING)},unmarshall:function(){this.rpid=this.popDXLong().value();this.type=this.popShort();this.greetings=this.popString()}});
IMMessage.IMGVCardInfo=Protocol.Message.extend({__category:"IM",__type:imConstant.Message.MSG_TYPE_GVCARD,uri:imConstant.IM.URI_IM_GVCARD_INFO,init:function(){this.guid=0;this.account=this.name="";this.subtype=this.type=0},marshall:function(){this.push(this.guid,bt.LONG);this.push(this.name,bt.STRING);this.push(this.account,bt.STRING);this.push(this.type,bt.SHORT);this.push(this.subtype,bt.SHORT)},unmarshall:function(){this.guid=this.popDXLong().value();this.name=this.popString();this.account=this.popString();
this.type=this.popShort();this.subtype=this.popShort()}});
IMMessage.IMPCallMessage=Protocol.Message.extend({__category:"IM",__type:imConstant.Message.MSG_TYPE_PCALL,uri:imConstant.IM.URI_IM_PCALL_INFO,init:function(){this.uid=0;this.roles=this.peerUid="";this.callDur=this.endTs=this.startTalkTs=this.startCallTs=this.callType=this.callStatus=0},marshall:function(){this.push(this.uid,bt.LONG);this.push(this.peerUid,bt.LONG);this.push(this.roles,bt.INT);this.push(this.callStatus,bt.INT);this.push(this.callType,bt.INT);this.push(this.startCallTs,bt.LONG);this.push(this.startTalkTs,
bt.LONG);this.push(this.endTs,bt.LONG);this.push(this.callDur,bt.LONG)},unmarshall:function(){this.uid=this.popDXLong().value();this.peerUid=this.popDXLong().value();this.roles=this.popInt();this.callStatus=this.popInt();this.callType=this.popInt();this.startCallTs=this.popDXLong().value();this.startTalkTs=this.popDXLong().value();this.endTs=this.popInt();this.callDur=this.popDXLong().value()}});
IMMessage.IMGeneralMessage=Protocol.Message.extend({__category:"IM",__type:imConstant.Message.MSG_TYPE_GENERAL,uri:imConstant.IM.URL_IM_GENERAL_INFO,init:function(){this.data={};this.type=0},marshall:function(){this.push(ByteBuffer.strToBytes(this.data),bt.BYTES);this.push(this.type,bt.INT)},unmarshall:function(){var a=this.popBytes(),b={};this.type=this.popInt();switch(this.type){case imConstant.GENERAL_TYPE.TYPE_CALL_1V1:var c=new Packet;c.buffer=new ByteBuffer(a);c.popInt();c.popInt();c.popShort();
b.creator=c.popUItem();b.invitee=c.popUItem();b.startTs=c.popDXLong().value();b.endTs=c.popDXLong().value();b.sid=c.popString();b.callType=c.popByte();b.callStatus=c.popByte();this.data=b;break;case imConstant.GENERAL_TYPE.TYPE_CALL_MEETING:c=new Packet;c.buffer=new ByteBuffer(a);c.popInt();c.popInt();c.popShort();b.creator=c.popUItem();b.startTs=c.popDXLong().value();b.endTs=c.popDXLong().value();b.gid=c.popDXLong().value();b.sid=c.popString();b.text=c.popString();this.data=b;break;case imConstant.GENERAL_TYPE.TYPE_GROUP_VOTE:this.data=
(new ByteBuffer(a)).readUTF8String(a.byteLength)}}});
IMMessage.IMNewEmotionMessage=Protocol.Message.extend({__category:"IM",__type:imConstant.Message.MSG_TYPE_NEWEMOTION,uri:imConstant.IM.URI_IM_NEWEMOTION_INFO,init:function(){this.params=this.type=this.name=this.id=this.packageName=this.packageId=this.category=""},marshall:function(){this.push(this.category,bt.STRING);this.push(this.packageId,bt.STRING);this.push(this.packageName,bt.STRING);this.push(this.id,bt.STRING);this.push(this.name,bt.STRING);this.push(this.type,bt.STRING);this.push(this.params,
bt.STRING)},unmarshall:function(){this.category=this.popString();this.packageId=this.popString();this.packageName=this.popString();this.id=this.popString();this.name=this.popString();this.type=this.popString();this.params=this.popString()}});var IMSession={};
IMSession.IMSendGroupMsgReq=Protocol.Response.extend({category:"IM",uri:imConstant.IM.URI_IM_SEND_GROUP_MSG,init:function(){this.uri=imConstant.IM.URI_IM_SEND_GROUP_MSG;this.deviceType=deviceInfo.deviceType;this.msgUuid=uuid.next();this.toGuid=this.fromUid=0;this.type;this.message;this.groupName=this.fromName="";this.cts=ctsTimer.get();this.msgId=0;this.extension="";this.retries=this.seqId=0;this.clusterId="";this.channel=this.receipt=0},setUid:function(a){this.fromUid=a},initAfter:function(){this.message&&
(this.type=this.type||this.message.__type)},marshall:function(){this.push(this.deviceType,bt.BYTE);this.push(this.msgUuid);this.push(this.fromUid,bt.LONG);this.push(this.toGuid,bt.LONG);this.push(this.message.__type);this.push(this.message);this.push(this.fromName);this.push(this.groupName);this.push(this.cts,bt.LONG);this.push(this.msgId,bt.LONG);this.push(this.extension);this.push(this.seqId,bt.LONG);this.push(this.retries,bt.BYTE);this.push(this.clusterId,bt.INT);this.push(this.receipt,bt.BYTE);
this.push(this.channel,bt.SHORT)},unmarshall:function(){this.deviceType=this.popByte();this.msgUuid=this.popString();this.fromUid=this.popDXLong().value();this.toGuid=this.popDXLong().value();this.type=this.popInt();this.message=Protocol.Message.fromBuffer(this.popBytes());this.fromName=this.popString();this.groupName=this.popString();this.cts=this.popDXLong().value();this.msgId=this.popDXLong();this.extension=this.popString();this.seqId=this.popDXLong().value();this.retries=this.popByte();this.clusterId=
this.popInt();this.receipt=this.popByte();this.channel=this.popShort()}});IMSession.IMSendGroupMsgRes=Protocol.Response.extend({category:"IM",uri:imConstant.IM.URI_IM_SEND_GROUP_MSG_RES,unmarshall:function(){this.msgUuid=this.popString();this.msgId=this.popDXLong().value();this.cts=this.popDXLong().value();this.rescode=this.popInt();this.deviceType=this.popByte();this.seqId=this.popDXLong().value();this.clusterId=this.popInt()}});
IMSession.IMGroupNotice=Protocol.Response.extend({category:"IM",uri:imConstant.IM.URI_IM_GROUP_NOTICE,init:function(){this.uri=imConstant.IM.URI_IM_GROUP_NOTICE;this.type=this.toGuid=0;this.data="";this.cts=0},marshall:function(){this.push(this.toGuid,bt.LONG);this.push(this.type);this.push(this.data)},unmarshall:function(){this.toGuid=this.popDXLong().value();this.type=this.popInt();this.data=this.popString()}});
IMSession.IMChatNotice=Protocol.Response.extend({category:"IM",uri:imConstant.IM.URI_IM_CHAT_NOTICE,init:function(){this.uri=imConstant.IM.URI_IM_CHAT_NOTICE;this.type=this.toUid=0;this.data="";this.cts=ctsTimer.get()},marshall:function(){this.push(this.toUid,bt.LONG);this.push(this.type);this.push(this.data);this.push(this.cts,bt.LONG)},unmarshall:function(){this.toUid=this.popDXLong().value();this.type=this.popInt();this.data=this.popString();this.cts=this.popDXLong().value()}});
IMSession.IMSendMsgReq=Protocol.Response.extend({category:"IM",uri:imConstant.IM.URI_IM_SEND_MSG,init:function(){this.uri=imConstant.IM.URI_IM_SEND_MSG;this.deviceType=deviceInfo.deviceType;this.msgUuid=uuid.next();this.toUid=this.fromUid=0;this.type;this.message;this.fromName="";this.cts=ctsTimer.get();this.msgId=0;this.toAppId=1;this.extension="";this.retries=this.seqId=0;this.clusterId="";this.channel=this.receipt=0},setUid:function(a){this.fromUid=a},initAfter:function(){this.message&&(this.type=
this.type||this.message.__type)},marshall:function(){this.push(this.deviceType,bt.BYTE);this.push(this.msgUuid);this.push(this.fromUid,bt.LONG);this.push(this.toUid,bt.LONG);this.push(this.message.__type);this.push(this.message);this.push(this.fromName);this.push(this.cts,bt.LONG);this.push(this.msgId,bt.LONG);this.push(this.toAppId,bt.SHORT);this.push(this.extension);this.push(this.seqId,bt.LONG);this.push(this.retries,bt.BYTE);this.push(this.clusterId,bt.INT);this.push(this.receipt,bt.BYTE);this.push(this.channel,
bt.SHORT)},unmarshall:function(){this.deviceType=this.popByte();this.msgUuid=this.popString();this.fromUid=this.popDXLong().value();this.toUid=this.popDXLong().value();this.type=this.popInt();this.message=Protocol.Message.fromBuffer(this.popBytes());this.fromName=this.popString();this.cts=this.popDXLong().value();this.msgId=this.popDXLong();this.toAppId=this.popShort();this.extension=this.popString();this.seqId=this.popDXLong().value();this.retries=this.popByte();this.clusterId=this.popInt();this.receipt=
this.popByte();this.channel=this.popShort();var a=userData.get("channelMap");this.channel&&0!==this.channel||(this.fromUid===userData.get("uid")?this.channel=a[this.toAppId]||0:this.channel=a[this.appid]||0)}});IMSession.IMSendMsgRes=Protocol.Response.extend({category:"IM",uri:imConstant.IM.URI_IM_SEND_MSG_RES,unmarshall:function(){this.msgUuid=this.popString();this.msgId=this.popDXLong().value();this.cts=this.popDXLong().value();this.rescode=this.popInt();this.deviceType=this.popByte()}});
IMSession.IMAckMsgs=Protocol.Request.extend({category:"IM",__master:!0,init:function(){this.uri=imConstant.IM.URI_IM_ACK_MSGS;this.deviceType=deviceInfo.deviceType;this.uid=0;this.msgIds=[]},marshall:function(){this.push(this.deviceType,bt.BYTE);this.push(this.uid,bt.LONG);this.push(this.msgIds)}});
IMSession.IMAckSyncMsgs=Protocol.Request.extend({__master:!0,category:"IM",init:function(){this.uri=imConstant.IM.URI_IM_ACK_SYNC_MSGS;this.deviceType=deviceInfo.deviceType;this.uid=0;this.msgIds=[]},marshall:function(){this.push(this.deviceType,bt.BYTE);this.push(this.uid,bt.LONG);this.push(this.msgIds)}});
IMSession.IMAckGroupMsgs=Protocol.Request.extend({__master:!0,category:"IM",init:function(){this.uri=imConstant.IM.URI_IM_ACK_GROUP_MSGS;this.deviceType=deviceInfo.deviceType;this.uid=0;this.msgIds=[]},marshall:function(){this.push(this.deviceType,bt.BYTE);this.push(this.uid,bt.LONG);this.push(this.msgIds)}});
IMSession.IMAckSyncGroupMsgs=Protocol.Request.extend({__master:!0,category:"IM",init:function(){this.uri=imConstant.IM.URI_IM_ACK_SYNC_GROUP_MSGS;this.deviceType=deviceInfo.deviceType;this.uid=0;this.msgIds=[]},marshall:function(){this.push(this.deviceType,bt.BYTE);this.push(this.uid,bt.LONG);this.push(this.msgIds)}});
IMSession.IMSyncRead=Protocol.Response.extend({category:"IM",uri:imConstant.IM.URI_IM_SYNC_READ,init:function(){this.uri=imConstant.IM.URI_IM_SYNC_READ;this.uid=0;this.deviceType=deviceInfo.deviceType;this.syncReadItems=[]},marshall:function(){this.push(this.uid,bt.LONG);this.push(this.deviceType,bt.BYTE);this.push(this.syncReadItems,bt.ARRAY_ARRAY)},unmarshall:function(){this.uid=this.popDXLong().value();this.deviceType=this.popByte();for(var a=this._popArrayArray(),b=0;b<a.length;b++)this.syncReadItems.push((new IMSession.IMSyncReadItem).parserFromBuffer(a[b]))}});
IMSession.IMSyncReadItem=Protocol.Request.extend({category:"IM",uri:imConstant.IM.URI_IM_SYNC_READ_ITEM,init:function(){this.uri=imConstant.IM.URI_IM_SYNC_READ_ITEM;this.chatId=0;this.stamp=ctsTimer.get();this.channel=this.sts=this.peerAppId=this.type=0},marshall:function(){this.push(this.chatId,bt.LONG);this.push(this.stamp,bt.LONG);this.push(this.type,bt.BYTE);this.push(this.peerAppId,bt.SHORT);this.push(this.sts,bt.LONG);this.push(this.channel,bt.SHORT)},unmarshall:function(){this.chatId=this.popDXLong().value();
this.stamp=this.popDXLong().value();this.type=this.popByte();this.peerAppId=this.popShort();this.sts=this.popDXLong().value();this.channel=this.popShort()}});
IMSession.IMCancelMsg=Protocol.Response.extend({category:"IM",uri:imConstant.IM.URI_IM_CANCEL_MSG,init:function(){this.uri=imConstant.IM.URI_IM_CANCEL_MSG;this.deviceType=deviceInfo.deviceType;this.msgUuid=uuid.next();this.toUid=this.fromUid=0;this.fromName="";this.cts=ctsTimer.get();this.msgId=0;this.toAppId=1;this.extension="";this.channel=0;this.isforce=!1},marshall:function(){this.push(this.deviceType,bt.BYTE);this.push(this.msgUuid);this.push(this.fromUid,bt.LONG);this.push(this.toUid,bt.LONG);
this.push(this.fromName);this.push(this.cts,bt.LONG);this.push(this.msgId,bt.LONG);this.push(this.toAppId,bt.SHORT);this.push(this.extension);this.push(this.channel,bt.SHORT);this.push(this.isforce,bt.SHORT)},unmarshall:function(){this.deviceType=this.popByte();this.msgUuid=this.popString();this.fromUid=this.popDXLong().value();this.toUid=this.popDXLong().value();this.fromName=this.popString();this.cts=this.popDXLong().value();this.msgId=this.popDXLong();this.toAppId=this.popShort();this.extension=
this.popString();this.channel=this.popShort();this.isforce=this.popShort()}});
IMSession.IMCancelMsgRes=Protocol.Response.extend({category:"IM",uri:imConstant.IM.URI_IM_CANCEL_MSG_RES,init:function(){this.uri=imConstant.IM.URI_IM_CANCEL_MSG_RES;this.deviceType=deviceInfo.deviceType;this.msgUuid=uuid.next();this.cts=ctsTimer.get();this.msgId=this.rescode=0},marshall:function(){this.push(this.msgUuid);this.push(this.msgId,bt.LONG);this.push(this.cts,bt.LONG);this.push(this.rescode,bt.INT);this.push(this.deviceType,bt.BYTE)},unmarshall:function(){this.msgUuid=this.popString();
this.msgId=this.popDXLong();this.cts=this.popDXLong().value();this.rescode=this.popInt();this.deviceType=this.popByte()}});
IMSession.IMCancelGroupMsg=Protocol.Response.extend({category:"IM",uri:imConstant.IM.URI_IM_CANCEL_GROUP_MSG,init:function(){this.uri=imConstant.IM.URI_IM_CANCEL_GROUP_MSG;this.deviceType=deviceInfo.deviceType;this.msgUuid=uuid.next();this.toGuid=this.fromUid=0;this.groupName=this.fromName="";this.cts=ctsTimer.get();this.msgId=0;this.extension="";this.channel=0;this.isforce=!1;this.adminUid=this.sts=0},marshall:function(){this.push(this.deviceType,bt.BYTE);this.push(this.msgUuid);this.push(this.fromUid,
bt.LONG);this.push(this.toGuid,bt.LONG);this.push(this.fromName);this.push(this.groupName);this.push(this.cts,bt.LONG);this.push(this.msgId,bt.LONG);this.push(this.extension);this.push(this.channel,bt.SHORT);this.push(this.isforce,bt.SHORT);this.push(this.sts,bt.LONG);this.push(this.adminUid,bt.LONG)},unmarshall:function(){this.deviceType=this.popByte();this.msgUuid=this.popString();this.fromUid=this.popDXLong().value();this.toGuid=this.popDXLong().value();this.fromName=this.popString();this.groupName=
this.popString();this.cts=this.popDXLong().value();this.msgId=this.popDXLong();this.extension=this.popString();this.channel=this.popShort();this.isforce=this.popShort();this.sts=this.popDXLong().value();this.adminUid=this.popDXLong().value()}});
IMSession.IMCancelGroupMsgRes=Protocol.Response.extend({category:"IM",uri:imConstant.IM.URI_IM_CANCEL_GROUP_MSG_RES,init:function(){this.uri=imConstant.IM.URI_IM_CANCEL_GROUP_MSG_RES;this.deviceType=deviceInfo.deviceType;this.msgUuid=uuid.next();this.cts=ctsTimer.get();this.msgId=this.rescode=0},marshall:function(){this.push(this.msgUuid);this.push(this.msgId,bt.LONG);this.push(this.cts,bt.LONG);this.push(this.rescode,bt.INT);this.push(this.deviceType,bt.BYTE)},unmarshall:function(){this.msgUuid=
this.popString();this.msgId=this.popDXLong();this.cts=this.popDXLong().value();this.rescode=this.popInt();this.deviceType=this.popByte()}});
IMSession.IMReceiptMsgReq=Protocol.Request.extend({category:"IM",uri:imConstant.IM.URI_IM_RECEIPT_MSG_REQ,init:function(){this.uri=imConstant.IM.URI_IM_RECEIPT_MSG_REQ;this.msgUuid=uuid.next();this.msgId=this.toUid=this.fromUid=0;this.cts=ctsTimer.get();this.deviceType=deviceInfo.deviceType;this.channel=0},marshall:function(){this.push(this.msgUuid);this.push(this.fromUid,bt.LONG);this.push(this.toUid,bt.LONG);this.push(this.msgId,bt.LONG);this.push(this.cts,bt.LONG);this.push(this.deviceType,bt.BYTE);
this.push(this.channel,bt.SHORT)},unmarshall:function(){this.msgUuid=this.popString();this.fromUid=this.popDXLong().value();this.toGuid=this.popDXLong().value();this.msgId=this.popDXLong().value();this.cts=this.popDXLong().value();this.deviceType=this.popByte();this.channel=this.popShort()}});
IMSession.IMReceiptMsgRes=Protocol.Response.extend({category:"IM",uri:imConstant.IM.URI_IM_RECEIPT_MSG_RES,init:function(){this.uri=imConstant.IM.URI_IM_RECEIPT_MSG_RES;this.msgUuid=uuid.next();this.msgId=0;this.cts=ctsTimer.get();this.deviceType=deviceInfo.deviceType;this.fromUid=0},marshall:function(){this.push(this.msgUuid);this.push(this.msgId,bt.LONG);this.push(this.cts,bt.LONG);this.push(this.deviceType,bt.BYTE);this.push(this.fromUid,bt.LONG)},unmarshall:function(){this.msgUuid=this.popString();
this.msgId=this.popDXLong().value();this.cts=this.popDXLong().value();this.deviceType=this.popByte();this.fromUid=this.popDXLong().value()}});
IMSession.IMReceiptGroupMsgReq=Protocol.Request.extend({category:"IM",uri:imConstant.IM.URI_IM_RECEIPT_GROUP_MSG_REQ,init:function(){this.uri=imConstant.IM.URI_IM_RECEIPT_GROUP_MSG_REQ;this.msgUuid=uuid.next();this.msgId=this.toUid=this.toGuid=this.fromUid=0;this.cts=ctsTimer.get();this.deviceType=deviceInfo.deviceType;this.channel=0},marshall:function(){this.push(this.msgUuid);this.push(this.fromUid,bt.LONG);this.push(this.toGuid,bt.LONG);this.push(this.toUid,bt.LONG);this.push(this.msgId,bt.LONG);
this.push(this.cts,bt.LONG);this.push(this.deviceType,bt.BYTE);this.push(this.channel,bt.SHORT)},unmarshall:function(){this.msgUuid=this.popString();this.fromUid=this.popDXLong().value();this.toGuid=this.popDXLong().value();this.toUid=this.popDXLong().value();this.msgId=this.popDXLong().value();this.cts=this.popDXLong().value();this.deviceType=this.popByte();this.channel=this.popShort()}});
IMSession.IMReceiptGroupMsgRes=Protocol.Response.extend({category:"IM",uri:imConstant.IM.URI_IM_RECEIPT_GROUP_MSG_RES,init:function(){this.uri=imConstant.IM.URI_IM_RECEIPT_GROUP_MSG_RES;this.msgUuid=uuid.next();this.msgId=0;this.cts=ctsTimer.get();this.fromUid=0;this.deviceType=deviceInfo.deviceType},marshall:function(){this.push(this.msgUuid);this.push(this.msgId,bt.LONG);this.push(this.cts,bt.LONG);this.push(this.fromUid,bt.LONG);this.push(this.deviceType,bt.BYTE)},unmarshall:function(){this.msgUuid=
this.popString();this.msgId=this.popDXLong().value();this.cts=this.popDXLong().value();this.fromUid=this.popDXLong().value();this.deviceType=this.popByte()}});
IMSession.IMMarkReads=Protocol.Response.extend({category:"IM",uri:imConstant.IM.URI_IM_MARK_READS,init:function(){this.uri=imConstant.IM.URI_IM_MARK_READS;this.uid="";this.deviceType=deviceInfo.deviceType;this.markReads=[]},marshall:function(){this.push(this.uid,bt.LONG);this.push(this.deviceType,bt.BYTE);this.push(this.markReads,bt.BTYES)},unmarshall:function(){this.uid=this.popDXLong().value();this.deviceType=this.popByte();for(var a=this._popArrayArray(),b=0;b<a.length;b++)this.markReads.push((new IMSession.IMMarkRead).parserFromBuffer(a[b]))}});
IMSession.IMMarkRead=Protocol.Response.extend({category:"IM",uri:imConstant.IM.URI_IM_MARK_READ,init:function(){this.uri=imConstant.IM.URI_IM_MARK_READ;this.chatAppId=this.chatType=this.chatId=0;this.opt=1;this.channel=0},marshall:function(){this.push(this.chatId,bt.LONG);this.push(this.chatType,bt.BYTE);this.push(this.chatAppId,bt.SHORT);this.push(this.opt,bt.BYTE);this.push(this.channel,bt.SHORT)},unmarshall:function(){this.chatId=this.popDXLong().value();this.chatType=this.popByte();this.chatAppId=
this.popShort();this.opt=this.popByte();this.channel=this.popShort()}});
IMSession.IMOppositeSyncRead=Protocol.Response.extend({category:"IM",uri:imConstant.IM.URI_IM_OPPOSITE_SYNC2_READ,init:function(){this.uid="";this.msgUuid=uuid.next();this.deviceType=deviceInfo.deviceType;this.syncReadItems=[]},marshall:function(){this.push(this.uid,bt.LONG);this.push(this.msgUuid,bt.STRING);this.push(this.deviceType,bt.BYTE);this.push(this.syncReadItems,bt.BYTES)},unmarshall:function(){this.uid=this.popDXLong().value();this.msgUuid=this.popString();this.deviceType=this.popByte();
for(var a=this._popArrayArray(),b=0;b<a.length;b++)this.syncReadItems.push((new IMSession.IMOppositeSyncReadItem).parserFromBuffer(a[b]))}});
IMSession.IMOppositeSyncReadItem=Protocol.Response.extend({category:"IM",uri:imConstant.IM.URI_IM_OPPOSITE_SYNC2_READ_ITEM,init:function(){this.chatId="";this.channel=this.peerAppId=this.type=0;this.msgIds=[]},marshall:function(){this.push(this.chatId,bt.LONG);this.push(this.type,bt.BYTE);this.push(this.peerAppId,bt.SHORT);this.push(this.channel,bt.SHORT);this.push(this.msgIds,bt.ARRAY_LONG)},unmarshall:function(){this.chatId=this.popDXLong().value();this.type=this.popByte();this.peerAppId=this.popShort();
this.channel=this.popShort();this.msgIds=this._popArrayDXLong()}});IMSession.IMOppositeSyncReadRes=Protocol.Response.extend({category:"IM",uri:imConstant.IM.URI_IM_OPPOSITE_SYNC2_READ_RES,init:function(){this.deviceType=this.msgUuid=this.uid=""},unmarshall:function(){this.uid=this.popDXLong().value();this.msgUuid=this.popString();this.deviceType=this.popByte()}});
var userDataStorage={},userData={set:function(a,b){userDataStorage[a]=b},setAll:function(a){extend(userDataStorage,a)},get:function(a){return userDataStorage[a]},getAll:function(){return extend({},userDataStorage)}};